#pragma once

#define PCI_CONFIG_ADDRESS 0x0CF8
#define PCI_CONFIG_DATA    0x0CFC

#define PCI_DEVICE_VENDOR_ID_OFFSET 0x00
#define PCI_DEVICE_DEVICE_ID_OFFSET 0x02
#define PCI_DEVICE_COMMAND_OFFSET 0x04
#define PCI_DEVICE_STATUS_OFFSET 0x06
#define PCI_DEVICE_REVISION_ID_OFFSET 0x08
#define PCI_DEVICE_PROG_IF_OFFSET 0x09
#define PCI_DEVICE_SUBCLASS_CLASS_CODE_OFFSET 0x0A
#define PCI_DEVICE_CACHE_LINE_SZ_OFFSET 0x0C
#define PCI_DEVICE_LATENCY_TIMER 0x0D
#define PCI_DEVICE_HEADER_TYPE_OFFSET 0x0E
#define PCI_DEVICE_BIST 0x0F

#define PCI_DEVICE_BAR0L_OFFSET 0x10
#define PCI_DEVICE_BAR0H_OFFSET 0x12

#define PCI_DEVICE_BAR1L_OFFSET 0x14
#define PCI_DEVICE_BAR1H_OFFSET 0x16

#define PCI_DEVICE_BAR2L_OFFSET 0x18
#define PCI_DEVICE_BAR2H_OFFSET 0x1A

#define PCI_DEVICE_BAR3L_OFFSET 0x1C
#define PCI_DEVICE_BAR3H_OFFSET 0x1E

#define PCI_DEVICE_BAR4L_OFFSET 0x20
#define PCI_DEVICE_BAR4H_OFFSET 0x22

#define PCI_DEVICE_BAR5L_OFFSET 0x24
#define PCI_DEVICE_BAR5H_OFFSET 0x26

#define PCI_DEVICE_INTERRUPT_LINE_OFFSET 0x3C
#define PCI_DEVICE_INTERRUPT_PIN_OFFSET 0x3D
#define PCI_DEVICE_PRIMARY_BUS_OFFSET 0x08
#define PCI_DEVICE_SECONDARY_BUS_OFFSET 0x19

#define PCI_HEADER_TYPE_MULTIFUNCTION (uint8_t)0x80
#define PCI_INVALID_VENDOR_ID (uint16_t)0xFFFF
#define PCI_BASE_CLASS_BRIDGE_DEVICE (uint8_t)0x06
#define PCI_SUB_CLASS_PCI_TO_PCI_BRIDGE (uint8_t)0x04
#define PCI_SUB_CLASS_PCI_TO_ISA_BRIDGE (uint8_t)0x01